name: "Main unit tests with mpich"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/miniforge:mpich
    steps:
      - name: Checkout Pace repository
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'
      - name: setup env and generate input files
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install -r requirements_dev.txt -c constraints.txt
          cd tests/main && mkdir -p input && cd input
          python3 ../../../examples/generate_eta_files.py
          cd ../../../
      - name:
        run: pytest -x tests/main
